import httpStatus from 'http-status'
import { validatePostResponse } from '../utils/validateMessageStatus'
import { credentials, signInUrl, baseUrl } from '../data'
import createServer from '../setup'
import chai from 'chai'
import chaiHttp from 'chai-http'
import create from '../../scripts/create-database'
import removeDatabase from '../setup/removeDatabase'
import config from '../setup/app.dev.config.json'
